---
title: "Tipos de filme de FULANO(A)"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(cluster)
library(plotly)
library(ggdendro)

source(here::here("code/lib.R"))
source(here("code/plota_solucoes_hclust.R"))

theme_set(theme_report())

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5,
                      echo = TRUE)

paleta = c("#404E4D",
           "#92DCE5",
           "#938BA1",
           "#2D3142",
           "#F4743B")
```

```{r}
games = read_csv(here("data/international-football.csv"))
```

# Preparando os dados

```{r}
jogos_brasil = games %>% 
    filter(home_team == "Brazil" | away_team == "Brazil") %>% 
    mutate(time1 = "Brazil", 
           time2 = if_else(home_team == "Brazil", away_team, home_team), 
           score1 = if_else(home_team == "Brazil", home_score, away_score),
           score2 = if_else(home_team == "Brazil", away_score, home_score) 
    ) 

historicos = jogos_brasil %>% 
    group_by(time2) %>% 
    summarise(
        jogos = n(),
        ganhou = sum(score1 > score2) / n(), 
        empatou = sum(score1 == score2) / n(),
        perdeu = sum(score1 < score2) / n()
        )
```


## Agrupamentos 

```{r}
agrupamento_h_2d = historicos %>% 
    as.data.frame() %>% 
    column_to_rownames("time2") %>%
    select(jogos, ganhou) %>%
    dist(method = "euclidean") %>% 
    hclust(method = "ward.D")

ggdendrogram(agrupamento_h_2d, rotate = TRUE)

data.frame(height = agrupamento_h_2d$height) %>% 
    mutate(k = 1:n()) %>% 
    ggplot(aes(x = k, y = height)) + 
    geom_line(colour = "grey") + 
    geom_point() + 
    labs(x = "Número de clusters produzido", y = "Dissimilaridade na junção")

```

**Solução: standardize (aka scale).**

```{r}
agrupamento_h_2d = filmes %>% 
    mutate_at(vars("avaliacao","bilheteria"), 
              funs(scale)) %>% 
    column_to_rownames("filme") %>%
    select("avaliacao", "bilheteria") %>%
    dist(method = "euclidean") %>% 
    hclust(method = "centroid")

ggdendrogram(agrupamento_h_2d, rotate = TRUE, theme_dendro = F)

plota_hclusts_2d(agrupamento_h_2d, 
                 filmes, 
                 c("avaliacao", "bilheteria"), 
                 linkage_method = "centroid", ks = 1:6) 

```

**Solução com Log**

```{r}
filmes %>% 
    ggplot(aes(x = bilheteria)) + 
    geom_histogram(bins = 30, fill = paleta[2], color = "black") +
    scale_x_log10()
```

```{r}
agrupamento_h_2d = filmes %>% 
    mutate(bilheteria = log10(bilheteria)) %>%
    mutate_at(vars("avaliacao", "bilheteria"), funs(scale)) %>%
    column_to_rownames("filme") %>%
    select("avaliacao", "bilheteria") %>%
    dist(method = "euclidean") %>% 
    hclust(method = "centroid")

ggdendrogram(agrupamento_h_2d, rotate = TRUE, theme_dendro = F)

filmes2 = filmes %>% mutate(bilheteria = log10(bilheteria))
plota_hclusts_2d(agrupamento_h_2d, 
                 filmes2, 
                 c("avaliacao", "bilheteria"), 
                 linkage_method = "centroid", ks = 1:6) + 
    scale_y_log10() + 
    scale_color_brewer(palette = "Dark2")
```
